### ISSUE TITLE
How do you combine CASL in this example, or in Mikroorm(mysql) 

### ISSUE THREAD

**Issue by 0x0bit** [mikro-orm/nestjs-realworld-example-app#122] opened 2024-12-27 01:55 UTC
In nestjs, how to use MikroORM and CASL, because CASL is very common, but I found a lot of online are combined with TypeORM or other, but for the combination of MikroORM materials are very few, can you provide an example in this example？thanks

**Comment by B4nan** [comment] 2024-12-27 09:00
closing as duplicate of https://github.com/mikro-orm/nestjs-example-app/issues/92

lets not spam multiple repositories like this, as said in the other issue, you should ask their maintainers, they should know better

**Closed by B4nan** 2024-12-27 09:00 UTC
