### ISSUE TITLE
NestJS v8 can't resolve dependencies when using EntityManager

### ISSUE THREAD

**Issue by adlanarifzr** [mikro-orm/nestjs-realworld-example-app#29] opened 2021-08-12 02:19 UTC
By upgrading NestJS to v8, importing `EntityManager` in the constructor would cause error "Nest can't resolve dependencies of the ...". Please help. Downgrading to v7 did not have this issue.

**Comment by B4nan** [comment] 2021-08-12 07:57
duplicate of https://github.com/mikro-orm/nestjs/issues/27

**Closed by B4nan** 2021-08-12 07:57 UTC
